config/routes.rb
Rails.application.routes.draw do
  get 'pages/start'

  get 'pages/home'

  get 'pages/about'

  get 'pages/contact'

  get 'pages/help'

  get 'pages/loginpage'

  devise_for :users

  resources :products
  resources :categories
  resources :manufacturers
  resources :sizes
  resources :locations

  root 'pages#start'

end

app/models/product.rb
class Product < ActiveRecord::Base

  belongs_to :user
  belongs_to :category
  belongs_to :manufacturer
  belongs_to :size
  belongs_to :location


  has_attached_file :prod_image, styles: { medium: '300x300>', thumb: '100x100>' }, default_url: '/images/:style/missing.png'
  validates_attachment_content_type :prod_image, content_type: /\Aimage\/.*\Z/

end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :set_product, only: [:show, :edit, :update, :destroy]

  # GET /products
  # GET /products.json
  def index

    if !params[:category].blank?
      @category_id = Category.find_by(name: params[:category]).id
      @products = Product.where(:category_id => @category_id)
      elsif !params[:size].blank?
        @size_id = Size.find_by(name: params[:size]).id
        @products = Product.where(:size_id => @size_id)
    elsif !params[:location].blank?
      @location_id = Location.find_by(name: params[:location]).id
      @products = Product.where(:location_id => @location_id)
    else
      @products = Product.all
    end



  end

  # GET /products/1
  # GET /products/1.json
  def show
  end

  # GET /products/new
  def new
    @product = current_user.products.build
    @categories = Category.all.map{ |c| [c.name, c.id] }
    @locations = Location.all.map{ |l| [l.name, l.id] }
    @manufacturers = Manufacturer.all.map{ |m| [m.name, m.id] }
    @sizes = Size.all.map{ |s| [s.name, s.id] }
  end

  # GET /products/1/edit
  def edit
    @categories = Category.all.map{ |c| [c.name, c.id] }
    @locations = Location.all.map{ |l| [l.name, l.id] }
    @manufacturers = Manufacturer.all.map{ |m| [m.name, m.id] }
    @sizes = Size.all.map{ |s| [s.name, s.id] }
  end

  # POST /products
  # POST /products.json
  def create
    @product = current_user.products.build(product_params)

    @product.category_id = params[:category_id]
    @product.manufacturer_id = params[:manufacturer_id]
    @product.size_id = params[:size_id]


    respond_to do |format|
      if @product.save
        format.html { redirect_to @product, notice: 'Product was successfully created.' }
        format.json { render :show, status: :created, location: @product }
      else
        format.html { render :new }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /products/1
  # PATCH/PUT /products/1.json
  def update
    @categories = Category.all.map{ |c| [c.name, c.id] }
    @manufacturers = Manufacturer.all.map{ |m| [m.name, m.id] }
    @sizes = Size.all.map{ |s| [s.name, s.id] }
    respond_to do |format|
      if @product.update(product_params)
        format.html { redirect_to @product, notice: 'Product was successfully updated.' }
        format.json { render :show, status: :ok, location: @product }
      else
        format.html { render :edit }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /products/1
  # DELETE /products/1.json
  def destroy
    @product.destroy
    respond_to do |format|
      format.html { redirect_to products_url, notice: 'Product was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_product
      @product = Product.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def product_params
      params.require(:product).permit(:product, :price, :description, :category_id, :manufacturer_id, :size_id, :location_id, :prod_image)
    end

  def find_product
    @product = Product.find(params[:id])
  end

end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/products/_form.html.erb
<%= simple_form_for @product, :html => { :multipart => true } do |f| %>
  <% if @product.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@product.errors.count, "error") %> prohibited this product from being saved:</h2>

      <ul>
      <% @product.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">

    <%= f.input :product %>
  </div>

    <div class="field">

      <%= select_tag(:category_id, options_for_select(@categories), :prompt => "Select A Catagory") %>
      <%= select_tag(:manufacturer_id, options_for_select(@manufacturers), :prompt => "Select A Manufacturer") %>
      <%= select_tag(:size_id, options_for_select(@sizes), :prompt => "Select A Size") %>
      <%= select_tag(:location_id, options_for_select(@locations), :prompt => "Add Your Location") %>
    </div>

  <div class="field">

    <%= f.input :price %>
  </div>
  <div class="field">

    <%= f.input :description %>
  </div>
    <div class="field">

      <%= f.file_field :prod_image %>
    </div>
  <div class="actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/products/edit.html.erb
<h1>Editing Product</h1>

<%= simple_form_for @product, :html => { :multipart => true } do |f| %>
    <% if @product.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(@product.errors.count, "error") %> prohibited this product from being saved:</h2>

          <ul>
            <% @product.errors.full_messages.each do |message| %>
                <li><%= message %></li>
            <% end %>
          </ul>
        </div>
    <% end %>

    <div class="field">

      <%= f.input :product %>
    </div>

    <div class="field">

      <%= f.select :category_id, @categories %>
      <%= f.select :manufacturer_id, @manufacturers %>
      <%= f.select :size_id, @sizes %>
      <%= f.select :location_id, @locations %>


    </div>

    <div class="field">

      <%= f.input :price %>
    </div>
    <div class="field">

      <%= f.input :description %>
    </div>
    <div class="field">

      <%= f.file_field :prod_image %>
    </div>
    <div class="actions">
      <%= f.button :submit %>
    </div>
<% end %>

<%= link_to 'Show', @product %> |
<%= link_to 'Back', products_path %>

app/views/products/index.html.erb
<h3 class="current-category"> <%= params[:category] %></h3>
<h3 class="current-size"><%= params[:size] %></h3>

<% if @products.count == 0 %>
    <h1>Sorry but there are no items currently available in your selection</h1>
    <% else %>

<h1>Listing Products</h1>

<div class="row">
    <% @products.each do |product| %>
        <div class="col-sm-4 col-md-3 col-lg-2">
            <p>
            <a href="/products/ <%= product.id %>">
             <%=  image_tag product.prod_image.url(:thumb), class: 'product' %></a>
            </p>
            <p>
                <%= link_to product.product, product %>
            </p>
            <p>
                <%= number_to_currency(product.price) %>
            </p>
        </div>

    <% end %>
</div>

<% end %>

app/views/products/new.html.erb
<h1>New Product</h1>

<%= render 'form' %>

<%= link_to 'Back', products_path %>

app/views/products/show.html.erb
<div class="row">
    <div class="col-sm-5 col-md-4 col-lg-3">
        <p>
             <%=  image_tag @product.prod_image.url(:medium), class: 'prodShow' %>
        </p>

    </div>
    <div class="col-sm-7 col-md-8 col-lg-9">
        <h2>
            <strong>Product:</strong>
            <%= @product.product %>
        </h2>

        <h3>
             <strong>Price:</strong>
            <%= @product.price %>
        </h3>

        <h4>
            <strong>Size:</strong>
            <%= @product.size.name %>
        </h4>

        <p>
            <strong>Description:</strong>
            <%= @product.description %>
        </p>
    </div>
</div>

<div class="row">
  <div class="col-sm-5 col-md-4 col-lg-3">

    <!-- Where teh reviews and ratings will go  -->

  </div>
</div>

<%= link_to 'Back', products_path %> |

<% if user_signed_in? %>
    <% if @product.user_id == current_user.id  %>
        <%= link_to 'Edit', edit_product_path(@product) %> |
        <%= link_to 'Destroy', method: :delete, data: { confirm: 'Are you sure?' } %>
    <% end %>
<% end %>