config/routes.rb
Rails.application.routes.draw do
  get 'pages/start'

  get 'pages/home'

  get 'pages/about'

  get 'pages/contact'

  get 'pages/help'

  get 'pages/loginpage'

  devise_for :users

  resources :products
  resources :categories
  resources :manufacturers
  resources :sizes
  resources :locations

  root 'pages#start'

end

app/models/location.rb
class Location < ActiveRecord::Base

  has_many :products

end

app/controllers/locations_controller.rb
class LocationsController < ApplicationController
  before_action :find_location, only: [:show, :edit, :update, :destroy]


  def index
    @locations = Location.all.order(:name)
  end

  def show
  end

  def new
    @location = Location.new
  end

  def create
    @location = Location.new(location_params)
    if @location.save
      redirect_to locations_path
    else
      render 'new'
    end
  end

  def edit

  end

  def update
    if @location.update(location_params)
      redirect_to location_path(@location)
    else
      render 'edit'
    end
  end

  def destroy
    @location.destroy
    redirect_to locations_path
  end

  private
  def location_params
    params.require(:location).permit(:name)
  end

  def find_location
    @location = Location.find(params[:id])
  end

end

app/helpers/locations_helper.rb
module LocationsHelper
end

app/views/locations/_form.html.erb
<%= simple_form_for @location do |f| %>

    <%= f.input :name, label: "Location Name" %>
    <%= f.button :submit %>

<% end %>

app/views/locations/edit.html.erb
<h1>Edit Location</h1>

<%= render 'form' %>

app/views/locations/index.html.erb
<h1>Listing Locations</h1>

<% @locations.each do |location| %>
    <h3><%= link_to location.name, location_path(location) %></h3>
<% end %>

<%= link_to "Add Location", new_location_path %>

app/views/locations/new.html.erb
<h1>Add New Location</h1>

<%= render 'form' %>

app/views/locations/show.html.erb
<h1>Show Location</h1>

<h2><%= @location.name %></h2>

<%= link_to "Back", locations_path %> |

<%= link_to "Edit", edit_location_path(@location) %> |
<%= link_to "Delete", location_path(@location), method: :delete, data: { confirm: "Are you sure?"} %>