config/routes.rb
Rails.application.routes.draw do
  get 'pages/start'

  get 'pages/home'

  get 'pages/about'

  get 'pages/contact'

  get 'pages/help'

  get 'pages/loginpage'

  devise_for :users

  resources :products
  resources :categories
  resources :manufacturers
  resources :sizes
  resources :locations

  root 'pages#start'

end

app/models/category.rb
class Category < ActiveRecord::Base

  has_many :products

end

app/models/location.rb
class Location < ActiveRecord::Base

  has_many :products

end

app/models/manufacturer.rb
class Manufacturer < ActiveRecord::Base

  has_many :products

end

app/models/product.rb
class Product < ActiveRecord::Base

  belongs_to :user
  belongs_to :category
  belongs_to :manufacturer
  belongs_to :size
  belongs_to :location


  has_attached_file :prod_image, styles: { medium: '300x300>', thumb: '100x100>' }, default_url: '/images/:style/missing.png'
  validates_attachment_content_type :prod_image, content_type: /\Aimage\/.*\Z/

end

app/models/size.rb
class Size < ActiveRecord::Base


  has_many :products

end

app/models/user.rb
class User < ActiveRecord::Base

  has_many :products

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :find_category, only: [:show, :edit, :update, :destroy]

  def index
    @categories = Category.all.order(:name)
  end

  def show
  end

  def new
    @category = Category.new
  end

  def create
    @category = Category.new(category_params)
    if @category.save
      redirect_to categories_path
    else
      render 'new'
    end
  end

  def edit

  end

  def update
    if @category.update(category_params)
      redirect_to category_path(@category)
    else
      render 'edit'
    end
  end

  def destroy
    @category.destroy
    redirect_to categories_path
  end

  private
  def category_params
    params.require(:category).permit(:name)
  end

  def find_category
    @category = Category.find(params[:id])
  end



end

app/controllers/locations_controller.rb
class LocationsController < ApplicationController
  before_action :find_location, only: [:show, :edit, :update, :destroy]


  def index
    @locations = Location.all.order(:name)
  end

  def show
  end

  def new
    @location = Location.new
  end

  def create
    @location = Location.new(location_params)
    if @location.save
      redirect_to locations_path
    else
      render 'new'
    end
  end

  def edit

  end

  def update
    if @location.update(location_params)
      redirect_to location_path(@location)
    else
      render 'edit'
    end
  end

  def destroy
    @location.destroy
    redirect_to locations_path
  end

  private
  def location_params
    params.require(:location).permit(:name)
  end

  def find_location
    @location = Location.find(params[:id])
  end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def start
    render params[:start], :layout => 'start'
  end

  def loginpage
    render params[:loginpage], :layout => 'start'
  end



  def home
  end

  def about
  end

  def contact
  end

  def help
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :set_product, only: [:show, :edit, :update, :destroy]

  # GET /products
  # GET /products.json
  def index

    if !params[:category].blank?
      @category_id = Category.find_by(name: params[:category]).id
      @products = Product.where(:category_id => @category_id)
      elsif !params[:size].blank?
        @size_id = Size.find_by(name: params[:size]).id
        @products = Product.where(:size_id => @size_id)
    elsif !params[:location].blank?
      @location_id = Location.find_by(name: params[:location]).id
      @products = Product.where(:location_id => @location_id)
    else
      @products = Product.all
    end



  end

  # GET /products/1
  # GET /products/1.json
  def show
  end

  # GET /products/new
  def new
    @product = current_user.products.build
    @categories = Category.all.map{ |c| [c.name, c.id] }
    @locations = Location.all.map{ |l| [l.name, l.id] }
    @manufacturers = Manufacturer.all.map{ |m| [m.name, m.id] }
    @sizes = Size.all.map{ |s| [s.name, s.id] }
  end

  # GET /products/1/edit
  def edit
    @categories = Category.all.map{ |c| [c.name, c.id] }
    @locations = Location.all.map{ |l| [l.name, l.id] }
    @manufacturers = Manufacturer.all.map{ |m| [m.name, m.id] }
    @sizes = Size.all.map{ |s| [s.name, s.id] }
  end

  # POST /products
  # POST /products.json
  def create
    @product = current_user.products.build(product_params)

    @product.category_id = params[:category_id]
    @product.manufacturer_id = params[:manufacturer_id]
    @product.size_id = params[:size_id]


    respond_to do |format|
      if @product.save
        format.html { redirect_to @product, notice: 'Product was successfully created.' }
        format.json { render :show, status: :created, location: @product }
      else
        format.html { render :new }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /products/1
  # PATCH/PUT /products/1.json
  def update
    @categories = Category.all.map{ |c| [c.name, c.id] }
    @manufacturers = Manufacturer.all.map{ |m| [m.name, m.id] }
    @sizes = Size.all.map{ |s| [s.name, s.id] }
    respond_to do |format|
      if @product.update(product_params)
        format.html { redirect_to @product, notice: 'Product was successfully updated.' }
        format.json { render :show, status: :ok, location: @product }
      else
        format.html { render :edit }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /products/1
  # DELETE /products/1.json
  def destroy
    @product.destroy
    respond_to do |format|
      format.html { redirect_to products_url, notice: 'Product was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_product
      @product = Product.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def product_params
      params.require(:product).permit(:product, :price, :description, :category_id, :manufacturer_id, :size_id, :location_id, :prod_image)
    end

  def find_product
    @product = Product.find(params[:id])
  end

end

app/controllers/sizes_controller.rb
class SizesController < ApplicationController
  before_action :find_size, only: [:show, :edit, :update, :destroy]


  def index
    @sizes = Size.all.order(:name)
  end

  def show
  end

  def new
    @size = Size.new
  end

  def create
    @size = Size.new(size_params)
    if @size.save
      redirect_to sizes_path
    else
      render 'new'
    end
  end

  def edit

  end

  def update
    if @size.update(size_params)
      redirect_to size_path(@size)
    else
      render 'edit'
    end
  end

  def destroy
    @size.destroy
    redirect_to sizes_path
  end

  private
  def size_params
    params.require(:size).permit(:name)
  end

  def find_size
    @size = Size.find(params[:id])
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/locations_helper.rb
module LocationsHelper
end

app/helpers/manufacturers_helper.rb
module ManufacturersHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/size_helper.rb
module SizeHelper
end

app/helpers/sizes_helper.rb
module SizesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>StylemeTest</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<nav class="navbar navbar-default">
  <div class="container">
    <div class="navbar-header">
      <%= link_to "Products", products_path, class: "navbar-brand" %>
    </div>
    <ul class="nav navbar-nav">
      <li><%= link_to "Sign Up", new_user_registration_path %></li>
      <% if user_signed_in? %>
          <li><%= link_to "Sign Out", destroy_user_session_path, method: :delete %></li>
      <% else %>
          <li><%= link_to "Log In", new_user_session_path %></li>
      <% end %>
    </ul>

    <ul class="nav navbar-nav navbar-right">
      <% if user_signed_in? %>
          <li><%= link_to "Add Product", new_product_path %></li>
      <% end %>
    </ul>


    <ul class="nav navbar-nav navbar-right">

      <li class="dropdown">
        <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">My Size <span class="caret"></span></a>
        <ul class="dropdown-menu" role="menu">
          <% Size.all.each do |size| %>
              <li class="<%= 'active' if params[:size] == size.name  %>">
                <%= link_to size.name, products_path(size: size.name), class: "link" %>
              </li>

          <% end %>
        </ul>
      </li>


      <li class="dropdown">
        <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Catagory <span class="caret"></span></a>
        <ul class="dropdown-menu" role="menu">
          <% Category.all.each do |category| %>
              <li class="<%= 'active' if params[:category] == category.name  %>">
                <%= link_to category.name, products_path(category: category.name), class: "link" %>
              </li>

          <% end %>
        </ul>
      </li>

      <li class="dropdown">
        <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Location<span class="caret"></span></a>
        <ul class="dropdown-menu" role="menu">
          <% Location.all.each do |location| %>
              <li class="<%= 'active' if params[:location] == location.name  %>">
                <%= link_to location.name, products_path(location: location.name), class: "link" %>
              </li>

          <% end %>
        </ul>
      </li>


      <% if user_signed_in? %>
      <li class="dropdown">
        <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Admin <span class="caret"></span></a>
        <ul class="dropdown-menu">
          <li><%= link_to 'Add Category', new_category_path %></li>
          <li><%= link_to 'Add Manufacturer', new_manufacturer_path %></li>
          <li><%= link_to 'Add Location', new_location_path %></li>
        </ul>
      </li>
      <% end %>
    </ul>


  </div>


</nav>

<p class="notice"><%= notice %></p>
<p class="alert"><%= alert %></p>

<div class="container">

<%= yield %>
</div>
</body>
</html>

app/views/layouts/start.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>StylemeTest</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/pages/about.html.erb
<h1>Pages#about</h1>
<p>Find me in app/views/pages/about.html.erb</p>

app/views/pages/contact.html.erb
<h1>Pages#contact</h1>
<p>Find me in app/views/pages/contact.html.erb</p>

app/views/pages/help.html.erb
<h1>Pages#help</h1>
<p>Find me in app/views/pages/help.html.erb</p>

app/views/pages/home.html.erb
<h1>Pages#home</h1>
<p>Find me in app/views/pages/home.html.erb</p>

app/views/pages/loginpage.html.erb
<div>

  <a href="/products/">
  <%=  image_tag ('iphone.png'), class: 'imgPage' %></a>




</div>

app/views/pages/start.html.erb
<div>

  <a href="/pages/loginpage/">
    <%=  image_tag ('iphone.png'), class: 'imgPage' %></a>




</div>